---

- name: Install Java repo
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: yes
  with_items:
    - repo: "ppa:webupd8team/java"

- name: Set debconf selections for java
  debconf: name='oracle-java{{ puppet_java_version }}-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Workaround for the Ansible 2.2 allow deb conf vtype seen
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: Install Oracle Java {{ puppet_java_version }}
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - "oracle-java{{ puppet_java_version }}-installer"

- name: Ensure JAVA_HOME environment variable set
  lineinfile:
    dest: /etc/environment
    line: "JAVA_HOME={{ puppet_java_home }}"
    regexp: "^JAVA_HOME=.*$"

- name: Update and install puppetserver
  apt:
    name: "puppetserver"
    update_cache: yes

- name: Ensure JVM Memory available
  lineinfile:
    line: 'JAVA_ARGS="-Xms3g -Xmx3g"'
    regexp: "JAVA_ARGS=.*"
    dest: "/ect/default/puppetserver"
    create: yes

- name: Template puppet conf
  template:
    src: "etc/puppetlabs/puppet/puppet.conf.j2"
    dest: "/etc/puppetlabs/puppet/puppet.conf"
  notify:
    - run systemctl deamon-reload
    - restart puppet server

- name: Template example manifest
  template:
    src: "etc/puppetlabs/code/environments/production/manifests/site.pp"
    dest: "/etc/puppetlabs/code/environments/production/manifests/site.pp"
    backup: yes

- name: Service start
  service:
    name: puppetserver
    state: started